### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by filmo** [danielballan/photomosaic#8]
mos = pm.untune(mosaic, img, orig_img)

should be:

 mos = pm.untune(mos, img, orig_img)

**Comment by danielballan** [comment]
Thanks @filmo. I'm returning to this project for the first time since 2012. I tagged that version as 0.1.0 and then completely rewrote the API to make it easier to customize intermediate steps. The new version is also significantly faster.

I'm closing this issue because it no longer applies. Sorry for not getting to it in a timely way. I'd be grateful for any comments on my re-written version if you are still interested.
